export default {
  "10003": { "name": "易筋经", "name_in_generator": "yi_jin_jing" },
  "10014": { "name": "紫霞功", "name_in_generator": "zi_xia_gong" },
  "10021": { "name": "花间游", "name_in_generator": "hua_jian_you" },
  "10175": { "name": "毒经", "name_in_generator": "du_jing" },
  "10225": { "name": "天罗诡道", "name_in_generator": "tian_luo_gui_dao" },
  "10268": { "name": "笑尘诀", "name_in_generator": "xiao_chen_jue" },
  "10390": { "name": "分山劲", "name_in_generator": "fen_shan_jing" },
  "10464": { "name": "北傲诀", "name_in_generator": "bei_ao_jue" },
  "10533": { "name": "凌海诀", "name_in_generator": "ling_hai_jue" },
  "10615": { "name": "太玄经", "name_in_generator": "tai_xuan_jing" },
  "10627": { "name": "无方", "name_in_generator": "wu_fang" },
  "101355": { "name": "无方_悟", "name_in_generator": "wu_fang_wu" },
  "10698": { "name": "孤锋诀", "name_in_generator": "gu_feng_jue" },
  "101375": { "name": "孤锋诀_悟", "name_in_generator": "gu_feng_jue_wu" },
  "10756": { "name": "山海心诀", "name_in_generator": "shan_hai_xin_jue" },
  "10786": { "name": "周天功", "name_in_generator": "zhou_tian_gong" },
  // "102278": {"name": "周天功_悟", "name_in_generator": "zhou_tian_gong_wu"},
  "10821": { "name": "幽罗引", "name_in_generator": "you_luo_yin" },
  "10144": { "name": "问水诀", "name_in_generator": "wen_shui_jue" },
  // "102278": {"name": "周天功_悟", "name_in_generator": "zhou_tian_gong_wu"},
}