export const attrMap = {
  "vitality_base": "属性类型.体质",
  "max_life_base": "属性类型.基础气血上限",
  "max_life_additional": "属性类型.额外气血上限",
  "max_life_add": "属性类型.额外气血上限",
  "strength_base": "属性类型.力道",
  "agility_base": "属性类型.身法",
  "spunk_base": "属性类型.元气",
  "spirit_base": "属性类型.根骨",
  "haste_base": "属性类型.加速等级",
  "strain_base": "属性类型.无双等级",
  "pvx_round": "属性类型.全能等级",
  "surplus_base": "属性类型.破招值",
  "physical_attack_power_base": "属性类型.外功基础攻击",
  "physical_critical_strike_base": "属性类型.外功会心等级",
  "physical_critical_power_base": "属性类型.外功会心效果等级",
  "physical_overcome_base": "属性类型.外功破防等级",
  "magical_attack_power_base": "属性类型.内功基础攻击",
  "all_critical_strike_base": "属性类型.全会心等级",
  "magical_critical_strike_base": "属性类型.内功会心等级",
  "all_critical_power_base": "属性类型.全会心效果等级",
  "magical_critical_power_base": "属性类型.内功会心效果等级",
  "magical_overcome_base": "属性类型.内功破防等级",
  "weapon_damage_base": "属性类型.武器伤害",
  strength_gain:'属性类型.郭氏力道',
  agility_gain:'属性类型.郭氏身法',
  spunk_gain:'属性类型.郭氏元气',
  spirit_gain:'属性类型.郭氏根骨',
  poison_attack_power_base: "属性类型.内功基础攻击",
  poison_overcome_base: "属性类型.内功破防等级",
  // all_major_base: "全属性",
}

export const WuCaiShiGainNameMeiju = {
  strength_base:'五彩石增益类型枚举.力道',
  agility_base:'五彩石增益类型枚举.身法',
  spunk_base:'五彩石增益类型枚举.元气',
  spirit_base:'五彩石增益类型枚举.根骨',
  haste_base:'五彩石增益类型枚举.加速等级',
  strain_base:'五彩石增益类型枚举.无双等级',
  surplus_base:'五彩石增益类型枚举.破招值',
  weapon_damage_base:'五彩石增益类型枚举.武器伤害',
  physical_attack_power_base:'五彩石增益类型枚举.外功基础攻击',
  physical_critical_strike_base:'五彩石增益类型枚举.会心等级',
  physical_critical_power_base:'五彩石增益类型枚举.会心效果等级',
  physical_overcome_base:'五彩石增益类型枚举.破防等级',
  magical_attack_power_base:'五彩石增益类型枚举.内功基础攻击',

  all_critical_strike_base:'五彩石增益类型枚举.会心等级',
  magical_critical_strike_base:'五彩石增益类型枚举.会心等级',

  all_critical_power_base:'五彩石增益类型枚举.会心效果等级',
  magical_critical_power_base:'五彩石增益类型枚举.会心效果等级',

  magical_overcome_base: '五彩石增益类型枚举.破防等级',
  strength_gain:'五彩石增益类型枚举.力道百分比',
  agility_gain:'五彩石增益类型枚举.身法百分比',
  spunk_gain:'五彩石增益类型枚举.元气百分比',
  spirit_gain:'五彩石增益类型枚举.根骨百分比',

  poison_attack_power_base: "五彩石增益类型枚举.内功基础攻击",
  poison_overcome_base: "五彩石增益类型枚举.破防等级",
}

export const filterNames = [
  "vitality",
  "neutral",
  "lunar",
  "neutral",
  "poison",
  "solar",
  "magical_shield_base",
  "all_major_base",
  "vitality_gain"
]