export const attrMap = {
  "vitality_base": "属性类型.体质",
  "max_life_base": "属性类型.基础气血上限",
  "max_life_additional": "属性类型.额外气血上限",
  "max_life_add": "属性类型.额外气血上限",
  "strength_base": "属性类型.力道",
  "agility_base": "属性类型.身法",
  "spunk_base": "属性类型.元气",
  "spirit_base": "属性类型.根骨",
  "haste_base": "属性类型.加速等级",
  "strain_base": "属性类型.无双等级",
  "pvx_round": "属性类型.全能等级",
  "surplus_base": "属性类型.破招值",
  "physical_attack_power_base": "属性类型.外功基础攻击",
  "physical_critical_strike_base": "属性类型.全会心等级",
  "physical_critical_power_base": "属性类型.全会心效果等级",
  "physical_overcome_base": "属性类型.全破防等级",
  "magical_attack_power_base": "属性类型.内功基础攻击",
  "poison_attack_power_base": "属性类型.内功基础攻击",
  "solar_attack_power_base": "属性类型.内功基础攻击",
  "neutral_attack_power_base": "属性类型.内功基础攻击",
  "lunar_attack_power_base": "属性类型.内功基础攻击",
  "solar_and_lunar_attack_power_base": "属性类型.内功基础攻击",
  "all_critical_strike_base": "属性类型.全会心等级",
  "magical_critical_strike_base": "属性类型.全会心等级",
  "neutral_critical_strike_base": "属性类型.全会心等级",
  "solar_critical_strike_base": "属性类型.全会心等级",
  "poison_critical_strike_base": "属性类型.全会心等级",
  "lunar_critical_strike_base": "属性类型.全会心等级",
  "solar_and_lunar_critical_strike_base": "属性类型.全会心等级",
  "all_critical_power_base": "属性类型.全会心效果等级",
  "magical_critical_power_base": "属性类型.全会心效果等级",
  "neutral_critical_power_base": "属性类型.全会心效果等级",
  "solar_critical_power_base": "属性类型.全会心效果等级",
  "poison_critical_power_base": "属性类型.全会心效果等级",
  "lunar_critical_power_base": "属性类型.全会心效果等级",
  "solar_and_lunar_critical_power_base": "属性类型.全会心效果等级",
  "magical_overcome_base": "属性类型.全破防等级",
  "poison_overcome_base": "属性类型.全破防等级",
  "neutral_overcome_base": "属性类型.全破防等级",
  "solar_overcome_base": "属性类型.全破防等级",
  "lunar_overcome_base": "属性类型.全破防等级",
  "solar_and_lunar_overcome_base": "属性类型.全破防等级"
}

export const 精简特效Map = {
  2697: '试炼鞋子破防',
  2702: '试炼鞋子破防',
  2698: '试炼适应之力',
  2703: '试炼适应之力',
  2699: '试炼项链破防',
  2704: '试炼项链破防',
  2700: '试炼腰坠破防',
  2705: '试炼腰坠破防',
  2701: '试炼暗器特效',
  2706: '试炼暗器特效',
  2707: '试炼项链会心',
  2708: '试炼项链会心',
  2709: '试炼鞋子会心',
  2710: '试炼鞋子会心',
  2711: '试炼腰坠会效',
  2712: '试炼腰坠会效',
  2770: '龙门飞剑武器',
  2814: '试炼鞋子破防',
  2819: '试炼鞋子破防',
  2815: '试炼适应之力',
  2820: '试炼适应之力',
  2816: '试炼项链破防',
  2821: '试炼项链破防',
  2817: '试炼腰坠破防',
  2822: '试炼腰坠破防',
  2818: '试炼暗器特效',
  2823: '试炼暗器特效',
  2824: '试炼项链会心',
  2825: '试炼项链会心',
  2826: '试炼鞋子会心',
  2827: '试炼鞋子会心',
  2828: '试炼腰坠会效',
  2829: '试炼腰坠会效',
  // 副本
  2869:'特效_2869',
  2870:'特效_2870',
  2871:'特效_2871',
  2872:'特效_2872',
  2873:'特效_2873',
  2874:'特效_2874',
  2875:'特效_2875',
  2876:'特效_2876',
  2880:'特效_2880',
}